global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'cpu-temp'
    static_configs:
      - targets: [cpu_temp:3000]
  - job_name: 'node-exporter'
    static_configs:
      - targets: [node_exporter:9100]
